const state={apiBase:localStorage.getItem('cryptoTraderApiBase')||window.location.origin,token:localStorage.getItem('cryptoTraderToken')||''};
let telegramStatus={configured:false,enabled:false,token_configured:false,chat_id:''};
const $=id=>document.getElementById(id);const money=v=>v==null?'-':`${Math.round(Number(v)).toLocaleString('ko-KR')}원`;const pct=v=>v==null?'-':`${Number(v).toFixed(2)}%`;const score=v=>v==null?'-':Number(v).toFixed(1);
class ApiError extends Error{constructor(status,body){super(`${status} ${body}`);this.status=status;this.body=body}}
function isLoopback(){const h=window.location.hostname;return h==='127.0.0.1'||h==='localhost'||h==='::1'}
function openConnectionSettings(message=''){if(message)$('connectionHint').textContent=message;$('apiBaseInput').value=state.apiBase;$('tokenInput').value=state.token;$('settingsDialog').showModal()}
async function api(path,options={}){const headers={...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;if(options.body&&typeof options.body!=='string'){headers['content-type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(`${state.apiBase}${path}`,{...options,headers});if(!r.ok){const body=await r.text();if(r.status===401&&!isLoopback()){localStorage.removeItem('cryptoTraderToken');state.token='';openConnectionSettings('인증 토큰이 없거나 만료됐습니다. PC 콘솔에 표시된 Dashboard token을 입력하세요.')}throw new ApiError(r.status,body)}return r.json()}
function assetCard(market,item){const s=item.signal||item,p=item.position||{};return `<article class="asset-card"><div class="row"><div><h3>${item.symbol||market.replace('KRW-','')}</h3><span class="market">${market}</span></div><div class="asset-actions"><span class="action ${s.action||''}">${s.action||'WAITING'}</span><button class="mini secondary remove-asset" data-market="${market}">삭제</button></div></div><div class="scores"><div class="score"><span>Regime</span><strong>${score(s.regime_score)}</strong></div><div class="score"><span>Entry</span><strong>${score(s.entry_score)}</strong></div><div class="score"><span>가격</span><strong>${item.price==null?'-':Number(item.price).toLocaleString('ko-KR')}</strong></div></div><div class="meta"><span>상대강도</span><b>${pct(s.asset_vs_majors_pct)}</b><span>조정폭</span><b>${pct(s.pullback_pct)}</b><span>호가 imbalance</span><b>${s.orderbook_imbalance==null?'-':Number(s.orderbook_imbalance).toFixed(3)}</b><span>평단</span><b>${p.avg_price?Number(p.avg_price).toLocaleString('ko-KR'):'-'}</b><span>보유가치</span><b>${money(p.value_krw)}</b><span>컨텍스트</span><b>${item.context_mode||'generic_alt'}</b></div></article>`}
function telegramLabel(){if(telegramStatus.enabled)return '활성';if(telegramStatus.configured)return '설정됨 · 비활성';return '미설정'}
async function loadTelegramStatus(){try{telegramStatus=await api('/api/telegram/status');return telegramStatus}catch{return telegramStatus}}
async function refresh(){try{const payload=await api('/api/state');$('connectionPill').textContent=isLoopback()?'로컬 연결됨':'연결됨';$('connectionPill').className='pill good';$('modeValue').textContent=payload.mode||'PAPER';$('equityValue').textContent=money(payload.portfolio?.equity_krw);$('cashValue').textContent=money(payload.portfolio?.cash_krw);$('ddValue').textContent=pct(payload.portfolio?.daily_drawdown_pct);$('engineStateText').textContent=payload.kill_switch?'KILL SWITCH 활성':payload.paused?'매수 일시정지':'정상 감시 중';const assets=payload.assets||{};$('assetGrid').innerHTML=Object.entries(assets).map(([m,i])=>assetCard(m,i)).join('')||'<div class="list-item">등록된 자산이 없습니다.</div>';document.querySelectorAll('.remove-asset').forEach(b=>b.onclick=async()=>{if(!confirm(`${b.dataset.market} 감시를 제거할까요?`))return;try{await api(`/api/assets/${encodeURIComponent(b.dataset.market)}`,{method:'DELETE'});await refresh()}catch(e){alert(e.message)}});const sync=payload.sync||{},backup=payload.backup||{};$('systemList').innerHTML=`<div class="list-item">Telegram: <b>${telegramLabel()}</b><small>${telegramStatus.chat_id?`Chat ID ${telegramStatus.chat_id}`:'대시보드에서 설정 가능'}</small></div><div class="list-item">GitHub sync: <b>${sync.status||'idle'}</b><small>${sync.to?String(sync.to).slice(0,7):''}</small></div><div class="list-item">Backup: <b>${backup.status||'idle'}</b><small>${backup.drive||''}</small></div><div class="list-item">업타임: <b>${Math.floor((payload.uptime_seconds||0)/60)}분</b></div>${payload.last_error?`<div class="list-item">최근 오류: <b>${payload.last_error.scope}</b><small>${payload.last_error.message}</small></div>`:''}`}catch(e){$('connectionPill').textContent='연결 필요';$('connectionPill').className='pill bad'}}
async function refreshFills(){try{const rows=await api('/api/fills?limit=20');$('fillsList').innerHTML=rows.map(r=>`<div class="list-item"><b>${r.market} ${r.side.toUpperCase()}</b> ${money(r.krw)} @ ${Number(r.price).toLocaleString('ko-KR')}<small>${new Date(r.ts*1000).toLocaleString('ko-KR')} · ${r.reason}</small></div>`).join('')||'<div class="list-item">아직 체결 기록이 없습니다.</div>'}catch{}}
$('settingsBtn').onclick=()=>openConnectionSettings(isLoopback()?'이 PC의 127.0.0.1 접속은 토큰 없이 자동 인증됩니다. 폰/LAN/Tailscale 접속에서만 Dashboard token이 필요합니다.':'PC 콘솔에 표시된 Dashboard token을 입력하세요.');$('saveSettings').onclick=()=>{state.apiBase=$('apiBaseInput').value.trim().replace(/\/$/,'')||window.location.origin;state.token=$('tokenInput').value.trim();localStorage.setItem('cryptoTraderApiBase',state.apiBase);if(state.token)localStorage.setItem('cryptoTraderToken',state.token);else localStorage.removeItem('cryptoTraderToken');setTimeout(()=>{loadTelegramStatus().then(refresh);refreshFills();loadRuntimeConfig()},0)};
$('addAssetForm').onsubmit=async e=>{e.preventDefault();const ticker=$('tickerInput').value.trim();if(!ticker)return;try{await api('/api/assets',{method:'POST',body:{ticker}});$('tickerInput').value='';await refresh()}catch(err){alert(err.message)}};
for(const [id,path] of [['pauseBtn','/api/control/pause'],['resumeBtn','/api/control/resume'],['killBtn','/api/control/kill'],['resetKillBtn','/api/control/reset-kill']])$(id).onclick=async()=>{try{await api(path,{method:'POST'});await refresh()}catch(e){alert(e.message)}};
$('telegramSettings').onclick=async()=>{await loadTelegramStatus();$('telegramTokenInput').value='';$('telegramTokenInput').placeholder=telegramStatus.token_configured?'토큰 저장됨 · 변경할 때만 입력':'BotFather에서 발급한 토큰';$('telegramChatIdInput').value=telegramStatus.chat_id||'';$('telegramEnabledInput').checked=!!telegramStatus.enabled;$('telegramStatusHint').textContent=telegramStatus.configured?'현재 텔레그램 설정이 이 PC에 로컬 저장되어 있습니다. 토큰은 화면에 다시 표시하지 않습니다.':'Bot token과 Chat ID를 입력하고 알림 활성화를 켜세요.';$('telegramDialog').showModal()};
$('saveTelegram').onclick=async e=>{e.preventDefault();const payload={enabled:$('telegramEnabledInput').checked,token:$('telegramTokenInput').value.trim(),chat_id:$('telegramChatIdInput').value.trim()};try{telegramStatus=await api('/api/telegram/config',{method:'PUT',body:payload});$('telegramDialog').close();await refresh();alert('텔레그램 설정을 저장했습니다.')}catch(err){alert(err.message)}};
$('telegramTest').onclick=async()=>{try{await api('/api/telegram/test',{method:'POST'});alert('텔레그램 테스트 메시지를 전송했습니다.')}catch(e){if(e.status===409){alert('텔레그램 설정이 아직 없습니다. 먼저 텔레그램 설정을 입력하세요.');$('telegramSettings').click();return}alert(e.message)}};$('backupNow').onclick=async()=>{try{await api('/api/backup',{method:'POST'});await refresh()}catch(e){alert(e.message)}};$('syncNow').onclick=async()=>{try{await api('/api/sync',{method:'POST'});await refresh()}catch(e){alert(e.message)}};$('refreshFills').onclick=refreshFills;
async function loadRuntimeConfig(){try{const cfg=await api('/api/config');for(const [key,value] of Object.entries(cfg)){const input=document.querySelector(`[data-config="${key}"]`);if(input)input.value=value}}catch{}}
$('runtimeConfigForm').onsubmit=async e=>{e.preventDefault();const payload={};document.querySelectorAll('[data-config]').forEach(input=>payload[input.dataset.config]=input.type==='number'?Number(input.value):input.value);try{await api('/api/config',{method:'PATCH',body:payload});alert('전략 설정 반영 및 GitHub 동기화 요청 완료');await loadRuntimeConfig()}catch(err){alert(err.message)}};
if(isLoopback()){localStorage.removeItem('cryptoTraderToken');state.token=''}
loadTelegramStatus().then(refresh);refreshFills();loadRuntimeConfig();setInterval(()=>loadTelegramStatus().then(refresh),5000);setInterval(refreshFills,15000);
